---
kind: Secret
apiVersion: v1
metadata:
  name: mlflow
#  labels:
#    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
stringData:
    provider: $PROVIDER
    client_id: $CLIENT_ID
    client_secret: $CLIENT_SECRET
    cookie_secret: $COOKIE_SECRET
    oidc_issuer_url: $OIDC_ISSUER_URL
    allowed_role: $ALLOWED_ROLE
    artifacts_destination: $ARTIFACTS_DESTINATION
    endpoint_url: $ENDPOINT_URL
    aws_access_key_id: $AWS_ACCESS_KEY_ID
    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    aws_bucket_name: $AWS_BUCKET_NAME
    postgresql_admin_password: $POSTGRESQL_ADMIN_PASSWORD
    postgresql_user: $POSTGRESQL_USER
    postgresql_password: $POSTGRESQL_PASSWORD
    postgresql_database: $POSTGRESQL_DATABASE
