---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-db
  labels:
    {{- include "mlflowdb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    {{- include "mlflowdb.selectorLabels" . | nindent 4 }}
