---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: http
    - port: 5500
      targetPort: 5500
      name: http-internal
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
