---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow.serviceAccountName" . }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"mlflow"}}'
